permalink: /:year/:month/:day/:title.html
paginate: 50
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: 廖浩帆
  email: fred.liao.bupt@gmail.com
  link: http://blog.csdn.net/f724430854
  github: https://github.com/fredliao123

# 站点信息
title: 廖浩帆的博客 
description: 廖浩帆的博客
url: http://fredliao123.github.io/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://img.my.csdn.net/uploads/201411/21/1416528891_3612.png
favicon: http://img.my.csdn.net/uploads/201411/21/1416528891_9081.png


# disqus 设置
disqus:
  shortname: fredliao123

# 主题设置，自动激活某个标签
active: 技术

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
